FROM ubuntu:14.04
#FROM docker-dev.yelpcorp.com/trusty_yelp
MAINTAINER Rob Johnson <robj@yelp.com>

RUN echo "deb http://repos.mesosphere.io/ubuntu/ trusty main" > /etc/apt/sources.list.d/mesosphere.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF && \
    apt-get update && \
    apt-get install -y maven \
    npm \
    mesos \
    && ln -s /usr/bin/nodejs /usr/bin/node
